#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov 18 18:42:12 2021

@author: pauljones
"""

import pandas as pd
import numpy as np
import statsmodels.api as st

# Generate data for the independent variables

np.random.seed(4)

x0 = np.ones(500)
x1 = np.random.normal(0, 1, 500)
x2 = np.random.normal(2, 4, 500)
x3 = np.random.normal(-1, 0.5, 500)

# Create independent variable and define the betas
y = 2 + 5*x1 -2*x2 + 1.5*x3 + np.random.normal(0, 1, 500)

# Create a matrix of independent variables
X = np.column_stack((x0, x1, x2, x3))

# Examine first 5 rows of X
X[:5]
